### ISSUE TITLE
Import csv form does not give you enough feedback when form is invalid

### ISSUE THREAD

**Issue by ArturoRomanelli** [enrique-lozano/Monekin#132]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

I tried to import a csv file, and as I arrived a the end of the form the button `import your data` was enabled, but when I tapped it, there was no sign from the app. Eventually I discovered that I left one of the previous dropdown field, the column for account with the choice`Unspecified`. There was no highlighting about the fact that the field was required, that something was missing. 

### Expected Behavior

I expect when I press the button that a snackbar or a dialog appears, or the step marker changes color to an error color.

### Steps to Reproduce

Try to import a file, continue the form leaving `Unspecified` in the account dropdownfield, try then to press the button `import your data`.

### Additional Information

As a side note, I wanted to contribute to this project, at least with the italian translation, or with this issue, when I try to debug, there's a problem with a missing file `mypath/Monekin/android/keys/key.properties`. I couldn't find either how to create it in the README.

**Comment by enrique-lozano** [comment]
Hi! First of all, thank you for bringing this issue and expressing your interest in contributing to the project.

I can successfully reproduce this behavior. I think the easiest thing to do at the moment would be to disable the continue button until the user selects a column for the account or a default account, similar to what happens in the category step. A snackbar there can do the work also. I will work on this as soon as possible.

Regarding the last thing you point out, for security reasons it is not good practice to upload the files with the application signature to the remote repository. However, I think this files are not necessary to run the app in debug mode. If you want to compile the app in release mode I think that it is necessary to use these files, so you will have to generate your own signature (see [here](https://developer.android.com/studio/publish/app-signing)). You should generate a `key.jks` file that contains the signature, and a `key.properties` with the credentials for that file. It is true that we miss some docs here, I should put a `README` in the android folder I think.

Anyway, if you don't want to mess around with this signature thing or it doesn't work for you, compile the application in Windows and everything should work practically the same.

**Comment by ArturoRomanelli** [comment]
Wondeful, disabling the continue button is surely a way to fix it for the moment. 

I will definitely look into the links you provided for generating the key, since
1. I will use the app on android and for some reason I cannot run it in debug mode without
2. Unfortunately I program either in linux or mac, so probably it's just easier to generate a key than install windows, download the project, reinitialize all flutter and so on.

Thank you for your quick response!

**Comment by enrique-lozano** [comment]
Hi! After some research today I have solved both problems:

- Now you can run the app on android without having to generate the signature files (solved in #136).

- When importing CSV, you can leave unchecked both the column for the accounts and the default account, creating in this case a new account with the name "Account Imported". Looking at the code, this was the expected behavior from the beginning, but a series of bugs prevented the app to finish the import flow (solved in #137).

Both problems are solved in the 'develop' branch, so you can try them now and if you have any new doubt, don't hesitate to ask again.

Thank you very much and I really appreciate your collaboration!
