### ISSUE TITLE
CSV Import Issue

### ISSUE THREAD

**Issue by Rafee-M** [enrique-lozano/Monekin#148]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

After creating a CSV export from the app I am unable to import it back

### Expected Behavior

Import data from the CSV file as shown with a the Paisa backup 

### Steps to Reproduce

1. Create backup from app
2. Import CSV backup
3. White screen appears

### Additional Information

Paisa backup:
[paisa_backup (1).csv](https://github.com/enrique-lozano/Monekin/files/15146803/paisa_backup.1.csv)

Monekin Backup:
[Transactions-20240429-14317.csv](https://github.com/enrique-lozano/Monekin/files/15146804/Transactions-20240429-14317.csv)

Video showing the error:

https://github.com/enrique-lozano/Monekin/assets/69535896/4c0c3905-3f30-43c4-b59e-fe15ec6e6f3c

**Comment by enrique-lozano** [comment]
Hi! First of all, thank you for reporting this issue.

I have located the bug, it only happens with csv files of less than 4-5 lines/transactions. This problem will be resolved in the next update.

**Comment by Rafee-M** [comment]
Thanks for the quick fix!
