### ISSUE TITLE
Category type both doesn't work

### ISSUE THREAD

**Issue by Jim8Knopf** [enrique-lozano/Monekin#222]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When the Category type is set to both (B) then it won't show up as an selection option. Not on income and not on expense.

### Expected Behavior

That it shows up and it's possible to select in both catagories

### Steps to Reproduce

I recognized it on 'Gifts & Donations'. It just didn't appeared for me anymore after the update. 

### Additional Information

I have the app version v7.1.0 installed.

Beside that i recognized that the selection isn't working anymore on my app. So I changed it directly in the database from B t E so I can use it for now. (Should I open a second ticket for this?)

**Comment by enrique-lozano** [comment]
Hi, thanks for using the app and for reporting this issue. I can reproduce this problem and I will try to fix it as soon as possible since it's really critical. Again, thanks for pointing out this.

**Comment by enrique-lozano** [comment]
Closed with #223, should be avalaible in Google Play soon with the release of `v7.1.1`!
