### ISSUE TITLE
Incomes that have category of both types result in expenses

### ISSUE THREAD

**Issue by vincius0000** [enrique-lozano/Monekin#234]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When creating an income transaction and using a category that is for both types (income & expense) then on balance calculation the income is seen as expense.

See _Steps to Reproduce_ section

### Expected Behavior

When creating income transaction the transaction amount should be positive, the category forces it to be negative.

### Steps to Reproduce

1. Create an account of initial balance of 2 euros
2. Create a category with type: Both (income & expense)
3. Create a transaction of type income and select newly created category, make the amount of transaction 2 euros
4. See the balance - it's 0 while it should be 4 euros

**Comment by vincius0000** [comment]
Screenshot of the income transaction that was initially entered as +2.00
![image](https://github.com/user-attachments/assets/b2c793eb-8905-43b3-8016-44ea9a7a9ea0)

Also if you do try to invert the transaction number from -2.00 to +2.00 then +2.00 is added to balance and in transaction number switches back to negative, resulting in me getting 2 euros out of air.

**Comment by enrique-lozano** [comment]
Thanks for the issue! I can reproduce this behavior, I will try to fix it as soon as possible
