### ISSUE TITLE
Overflow in the total balance amount when using large numbers and currencies

### ISSUE THREAD

**Issue by valxyra** [enrique-lozano/Monekin#256]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When using Rupiah currency with a balance amount of more than Rp1,000,000 (approx. $63), the Expense and Income display appears out of the container.

![Screenshot_monekin](https://github.com/user-attachments/assets/face5fa5-76c3-43d5-90c4-1e778a726fbd)

### Expected Behavior

When using currencies with lengthy balances, the font size should change responsively or perhaps the Expense and Income displays should move below the Total balance.

### Steps to Reproduce

1. Create an account
2. Choose Rupiah currency
3. Enter a balance amount of Rp1,000,000 (approx. $63) or Rp10,000,000 (approx. $630)
4. Go to dashboard

**Comment by enrique-lozano** [comment]
Thanks for the issue, it's really clear that the app is not prepared for this type of currencies with high inflation rates😅.

I am thinking of removing that income-expense indicator of the header and put It below as other card un the Dashboard. What do you think?

**Comment by valxyra** [comment]
> I am thinking of removing that income-expense indicator of the header and put It below as other card in the Dashboard. What do you think?

Yes, I think that's a good idea.🙆‍♂️

**Comment by enrique-lozano** [comment]
Closed with #267, the solution is explained in the PR 🚀
