### ISSUE TITLE
App crashes when selecting Expense Category 

### ISSUE THREAD

**Issue by bikeophilipp** [enrique-lozano/Monekin#263]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/enrique-lozano/Monekin/blob/main/CONTRIBUTING.md#reporting-issues).
- [X] I agree to follow the [Code of Conduct](https://github.com/enrique-lozano/Monekin/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/enrique-lozano/Monekin/issues?q=is%3Aissue) that already report this problem, without success.
- [X] I have updated the app to the last released version.

### Current Behavior

When adding a transaction and selecting a category, it crashes shortly after selecting one.
This only happens in the **Expense** category and not in the Income category.

Using latest version of the App, downloaded from GitHub, running GrapheneOS on a Pixel 8.

### Expected Behavior

Selecting Expense category without App crashing.

### Steps to Reproduce

Open the App. 
Add a Expense Transaction.
Select Category —> Crash

**Comment by enrique-lozano** [comment]
Hi! Honestly, it's a pretty rare issue. Can you provide more details about it? Have you selected a category or a subcategory? Did the selected category have any subcategories? If so, how many? If you could upload a video with the issue, that would be much better.

I'm testing with an Android 14 and I don't have any problems with any expense category. May be something related to GrapheneOS?

**Comment by bikeophilipp** [comment]
Sure, no problem. 
Here you go. I also added the Crash Report if this helps. 
You see in the video that it does not crash when adding income, but it does when adding expenses. 
It was a completely fresh install of the App. 

Might be GrapheneOS, this is why I have mentioned it. 

https://github.com/user-attachments/assets/4963def0-5d8e-4615-b5b5-304d747e5377


[Error in Monekin 8f1423f0d469.txt](https://github.com/user-attachments/files/18135544/Error.in.Monekin.8f1423f0d469.txt)

**Comment by enrique-lozano** [comment]
Wow, really really weird, I will look into it, thanks!

**Comment by bikeophilipp** [comment]
Awesome, thanks for you help.
I was checking the older versions.
It works in Version 6.1.0 but with 7.0.0 it starts crashing.

By the way, the design really made a big jump. It looks so awesome in the latest version.

**Comment by enrique-lozano** [comment]
Probably this is a database issue. Please send me yours at lozin.technologies@gmail.com if you don't mind.

**Comment by bikeophilipp** [comment]
Short update. Not sure what you fixed but I tried 7.3.0 and now it does not crash anymore.
Thanks a lot. Now I can use it.

**Comment by enrique-lozano** [comment]
> Short update. Not sure what you fixed but I tried 7.3.0 and now it does not crash anymore. Thanks a lot. Now I can use it.

Hi! I'm glad it's fixed. It's funny because I haven't really touched anything about it 😂. 

Maybe [the upgrade of the Grandle's version](https://github.com/enrique-lozano/Monekin/commit/207d00e0d22c0dc68de611a25febd3f9519f6ae5) made the problem go away, but I really don't know. Since the cause is not known, it is quite likely that the problem will occur again, so if it happens again we will reopen this issue.
